# Generated by Django 2.0.2 on 2018-03-20 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('novels', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='novel',
            old_name='bookcase_id',
            new_name='bookcase',
        ),
    ]
