# Generated by Django 2.0.2 on 2018-03-20 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novels', '0002_auto_20180320_1656'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='novel',
            name='file_path',
        ),
        migrations.AddField(
            model_name='novel',
            name='file',
            field=models.FileField(max_length=500, null=True, upload_to='uploads/'),
        ),
    ]
