# Generated by Django 2.0.2 on 2018-03-21 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novels', '0003_auto_20180320_2127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='novel',
            name='published_date',
            field=models.DateField(),
        ),
    ]
